-- =========================================
-- REINSERTAR ACCIONES (SIN ERRORES)
-- =========================================

INSERT INTO pedidosjb_seguridad.accion
(idaccion, idopcion, nombre, indOpcion, referencia1, referencia2, referencia3, estado)
VALUES
(1,1,'opcion usuarios','SI',NULL,NULL,NULL,'ACTIVO'),
(2,1,'Crear_usuario','NO','usuario',NULL,NULL,'ACTIVO'),
(3,1,'Modificar_usuario','NO','usuario',NULL,NULL,'ACTIVO'),
(4,1,'Cambiar_clave_usuario','NO','usuario',NULL,NULL,'ACTIVO'),
(5,2,'opcion roles de usuario','SI',NULL,NULL,NULL,'ACTIVO'),
(6,2,'Crear_rol','NO','rol',NULL,NULL,'ACTIVO'),
(7,2,'Modificar_rol','NO','rol',NULL,NULL,'ACTIVO'),
(8,3,'opcion permisos por rol','SI',NULL,NULL,NULL,'ACTIVO'),
(9,3,'Cargar_permisos_rol','NO','rol',NULL,NULL,'ACTIVO'),
(10,3,'Agregar_permiso_accion','NO','rol','accion',NULL,'ACTIVO'),
(11,3,'Retirar_permiso_accion','NO','rol','accion',NULL,'ACTIVO'),
(12,1,'Cambiar_estado_usuario','NO','usuario','estado nuevo',NULL,'ACTIVO'),
(13,2,'Cambiar_estado_rol','NO','rol',NULL,NULL,'ACTIVO'),
(14,3,'Agregar_opcion_accion','NO','rol','accion',NULL,'ACTIVO'),
(15,3,'Retirar_opcion_accion','NO','rol','accion',NULL,'ACTIVO'),
(16,4,'opcion Bitacora','SI',NULL,NULL,NULL,'ACTIVO'),
(17,4,'Consultar_bitacora','NO','usuario','desde','hasta','ACTIVO'),
(18,5,'opcion configuracion','SI',NULL,NULL,NULL,'ACTIVO'),
(19,5,'Modificar_configuracion','NO','clave',NULL,NULL,'ACTIVO'),
(20,6,'Opcion orden de menus','SI',NULL,NULL,NULL,'ACTIVO'),
(21,6,'Modificar_orden_de_menus','NO','menu',NULL,NULL,'ACTIVO'),
(22,7,'Opcion carga productos','SI',NULL,NULL,NULL,'ACTIVO'),
(23,7,'Cargar_productos','NO',NULL,NULL,NULL,'ACTIVO'),
(24,7,'Crear_producto_carga_productos','NO',NULL,NULL,NULL,'ACTIVO'),
(25,7,'Crear_color_producto_precio_carga_productos','NO',NULL,NULL,NULL,'ACTIVO'),
(26,7,'Eliminar_productos_borrador_carga_productos','NO',NULL,NULL,NULL,'ACTIVO'),
(27,7,'Activar_productos_carga_productos','NO',NULL,NULL,NULL,'ACTIVO'),
(28,7,'Modificar_producto_carga_productos','NO',NULL,NULL,NULL,'ACTIVO'),
(29,7,'Crear_producto_precio_carga_productos','NO',NULL,NULL,NULL,'ACTIVO'),
(30,7,'Eliminar productos','NO',NULL,NULL,NULL,'ACTIVO'),
(31,7,'Activar productos','NO',NULL,NULL,NULL,'ACTIVO'),
(32,7,'Crear set de talla','NO',NULL,NULL,NULL,'ACTIVO'),
(33,7,'Crear detalle set de talla','NO',NULL,NULL,NULL,'ACTIVO'),
(34,7,'Modificar producto','NO',NULL,NULL,NULL,'ACTIVO'),
(35,7,'Modificar producto precio','NO',NULL,NULL,NULL,'ACTIVO'),
(36,8,'Opcion_cliente','SI','idcliente',NULL,NULL,'ACTIVO'),
(37,8,'Crear_cliente','NO','idcliente',NULL,NULL,'ACTIVO'),
(38,8,'Modificar_cliente','NO','idcliente',NULL,NULL,'ACTIVO'),
(39,8,'Cambiar_estado_cliente','NO','idcliente',NULL,NULL,'ACTIVO'),
(40,9,'Opcion pedido','SI',NULL,NULL,NULL,'ACTIVO'),
(41,9,'Crear_pedido','NO',NULL,NULL,NULL,'ACTIVO'),
(42,9,'Eliminar_pedido','NO',NULL,NULL,NULL,'ACTIVO'),
(43,9,'Cerrar_pedido','NO',NULL,NULL,NULL,'ACTIVO'),
(44,9,'Crear_detalle_pedido','NO',NULL,NULL,NULL,'ACTIVO'),
(45,9,'Eliminar_detalle_pedido','NO',NULL,NULL,NULL,'ACTIVO'),
(46,9,'Modificar_detalle_pedido','NO',NULL,NULL,NULL,'ACTIVO'),
(47,9,'Imprimir_pedido','NO',NULL,NULL,NULL,'ACTIVO'),
(48,10,'Opcion producto','SI',NULL,NULL,NULL,'ACTIVO'),
(49,10,'Crear_producto_mantenimiento','NO',NULL,NULL,NULL,'ACTIVO'),
(50,10,'Modificar_producto_mantenimiento','NO',NULL,NULL,NULL,'ACTIVO'),
(51,10,'Cambiar_estado_producto_mantenimiento','NO',NULL,NULL,NULL,'ACTIVO'),
(52,10,'Crear_producto_precio_mantenimiento','NO',NULL,NULL,NULL,'ACTIVO'),
(53,10,'Modificar_producto_precio_mantenimiento','NO',NULL,NULL,NULL,'ACTIVO')

ON DUPLICATE KEY UPDATE
    idopcion = VALUES(idopcion),
    nombre = VALUES(nombre),
    indOpcion = VALUES(indOpcion),
    referencia1 = VALUES(referencia1),
    referencia2 = VALUES(referencia2),
    referencia3 = VALUES(referencia3),
    estado = VALUES(estado);